import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as MailComposer from "expo-mail-composer";
import { printHtml, shareOrPrintHtml } from "@/utils/pdf/pdfPrint";
import { HydrostaticTest } from "@/types/hydrostaticTest";
import { Inspection, InspectionPhoto } from "@/contexts/InspectionContext";
import { ensureAllPhotosBase64 } from "@/utils/photoUtils";
import { sanitizeHtml, PDF_THEME } from "./pdfTheme";
import { renderHeader, renderFooter, wrapDocument } from "./pdfLayout";
import { getLogoDataUri } from "./pdfAssets";

interface HydrostaticPdfOptions {
  inspection: Inspection;
  hydrostaticTest: HydrostaticTest;
  photos: InspectionPhoto[];
  language: "en" | "pt-BR";
}

const translations = {
  en: {
    title: "HYDROSTATIC TEST REPORT",
    subtitle: "Fire Protection System",
    testIdentification: "TEST IDENTIFICATION",
    systemType: "System Type",
    hydrants: "Hydrants",
    sprinklers: "Sprinklers",
    systemName: "System Name",
    buildingType: "Building Type",
    protectedArea: "Protected Area",
    normativeReferences: "Normative References",
    fmDataSheet: "FM Global Data Sheet",
    nbrStandard: "NBR Standard",
    approvedBy: "Project Approved by",
    cb: "Fire Department",
    fm: "FM Global",
    other: "Other",
    testDate: "Test Date",
    startTime: "Start Time",
    endTime: "End Time",
    weather: "Weather Conditions",
    weatherSunny: "Sunny",
    weatherCloudy: "Cloudy",
    weatherRainy: "Rainy",
    weatherPartlyCloudy: "Partly Cloudy",
    weatherStormy: "Stormy",
    partiesInvolved: "PARTIES INVOLVED",
    owner: "Owner/Client",
    corporateName: "Corporate Name",
    address: "Address",
    localResponsible: "Local Responsible",
    role: "Role/Position",
    contact: "Contact",
    executorCompany: "Executor Company",
    cnpj: "CNPJ/Tax ID",
    technicalResponsible: "Technical Responsible",
    name: "Name",
    creaCau: "CREA/CAU",
    artRrt: "ART/RRT",
    inspector: "Inspector",
    preparation: "PREPARATION",
    preChecks: "Pre-Checks",
    installedAsApprovedProject: "System installed as per approved project",
    pipesAnchoredAndSupported: "Pipes properly anchored and supported",
    valvesCorrectlyInstalled: "Valves correctly installed and accessible",
    visibleConnectionsAccessible: "Visible connections accessible",
    untestedSectionsIsolated: "Untested sections isolated",
    sensitiveEquipmentProtected: "Sensitive equipment protected",
    instrumentation: "Instrumentation",
    manometerBrand: "Manometer Brand",
    manometerModel: "Model",
    measurementRange: "Measurement Range",
    calibrationCertificate: "Calibration Certificate",
    pressureReadingPoint: "Pressure Reading Point",
    highestPoint: "Highest Point",
    nearPump: "Near Pump",
    otherPoint: "Other",
    execution: "EXECUTION",
    filling: "Filling",
    fillingMethod: "Filling Method",
    gradual: "Gradual",
    bySector: "By Sector",
    airElimination: "Air Elimination",
    reliefValvesOpen: "Relief valves open",
    purgersUsed: "Purgers used",
    pressure: "Pressure",
    workingPressure: "Working Pressure",
    testPressure: "Test Pressure",
    normativeCriteria: "Normative Criteria Applied",
    minimumTestTime: "Minimum Test Time",
    minutes: "min",
    hours: "h",
    monitoring: "Monitoring",
    stabilizationStartTime: "Stabilization Start Time",
    testEndTime: "Test End Time",
    initialPressure: "Initial Pressure",
    finalPressure: "Final Pressure",
    pressureVariation: "Pressure Variation",
    results: "RESULTS",
    tightness: "Tightness",
    noLeaks: "No leaks found",
    noPressureDrop: "No pressure drop",
    noVisibleDeformation: "No visible deformation",
    occurrences: "Occurrences",
    leaksFound: "Leak(s) found",
    leaksDescription: "Leak(s) Description",
    pressureDropAboveAllowed: "Pressure drop above allowed",
    structuralFailure: "Structural failure",
    failureDescription: "Failure Description",
    photoEvidence: "PHOTO EVIDENCE",
    initialGaugePhotos: "Initial - Gauge",
    initialGeneralPhotos: "Initial - General View",
    duringTestPhotos: "During Test",
    finalGaugePhotos: "Final - Gauge",
    finalGeneralPhotos: "Final - General View",
    conclusion: "TECHNICAL CONCLUSION",
    status: "Status",
    approved: "APPROVED",
    reproved: "REPROVED",
    technicalConclusion: "Technical Conclusion",
    declarationSignatures: "DECLARATION & SIGNATURES",
    declarationText: "I declare that all information provided in this report is true and that the test was conducted in accordance with applicable standards.",
    technicalResponsibleSignature: "Technical Responsible",
    inspectorSignature: "Inspector",
    ownerRepSignature: "Owner Representative",
    date: "Date",
    yes: "Yes",
    no: "No",
    generatedBy: "Generated by FireSafe ITM",
    geolocation: "Geolocation",
    latitude: "Latitude",
    longitude: "Longitude",
    accuracy: "Accuracy",
    meters: "m",
  },
  "pt-BR": {
    title: "RELATORIO DE TESTE HIDROSTATICO",
    subtitle: "Sistema de Protecao Contra Incendio",
    testIdentification: "IDENTIFICACAO DO TESTE",
    systemType: "Tipo de Sistema",
    hydrants: "Hidrantes",
    sprinklers: "Sprinklers",
    systemName: "Nome do Sistema",
    buildingType: "Tipo de Edificacao",
    protectedArea: "Area Protegida",
    normativeReferences: "Normas de Referencia",
    fmDataSheet: "Data Sheet FM Global",
    nbrStandard: "Norma NBR",
    approvedBy: "Projeto Aprovado por",
    cb: "Corpo de Bombeiros",
    fm: "FM Global",
    other: "Outro",
    testDate: "Data do Teste",
    startTime: "Hora Inicio",
    endTime: "Hora Termino",
    weather: "Condicoes Climaticas",
    weatherSunny: "Ensolarado",
    weatherCloudy: "Nublado",
    weatherRainy: "Chuvoso",
    weatherPartlyCloudy: "Parcialmente Nublado",
    weatherStormy: "Tempestuoso",
    partiesInvolved: "PARTES ENVOLVIDAS",
    owner: "Proprietario/Contratante",
    corporateName: "Razao Social",
    address: "Endereco",
    localResponsible: "Responsavel Local",
    role: "Cargo/Funcao",
    contact: "Contato",
    executorCompany: "Empresa Executora",
    cnpj: "CNPJ",
    technicalResponsible: "Responsavel Tecnico",
    name: "Nome",
    creaCau: "CREA/CAU",
    artRrt: "ART/RRT",
    inspector: "Inspetor",
    preparation: "PREPARACAO",
    preChecks: "Verificacoes Previas",
    installedAsApprovedProject: "Sistema instalado conforme projeto aprovado",
    pipesAnchoredAndSupported: "Tubulacoes ancoradas e suportadas adequadamente",
    valvesCorrectlyInstalled: "Valvulas corretamente instaladas e acessiveis",
    visibleConnectionsAccessible: "Conexoes visiveis e acessiveis",
    untestedSectionsIsolated: "Trechos nao testados isolados",
    sensitiveEquipmentProtected: "Equipamentos sensiveis protegidos",
    instrumentation: "Instrumentacao",
    manometerBrand: "Marca do Manometro",
    manometerModel: "Modelo",
    measurementRange: "Faixa de Medicao",
    calibrationCertificate: "Certificado de Calibracao",
    pressureReadingPoint: "Ponto de Leitura de Pressao",
    highestPoint: "Ponto mais Alto",
    nearPump: "Proximo a Bomba",
    otherPoint: "Outro",
    execution: "EXECUCAO",
    filling: "Enchimento",
    fillingMethod: "Metodo de Enchimento",
    gradual: "Gradual",
    bySector: "Por Setor",
    airElimination: "Eliminacao de Ar",
    reliefValvesOpen: "Valvulas de alivio abertas",
    purgersUsed: "Purgadores utilizados",
    pressure: "Pressao",
    workingPressure: "Pressao de Trabalho",
    testPressure: "Pressao de Teste",
    normativeCriteria: "Criterio Normativo Aplicado",
    minimumTestTime: "Tempo Minimo de Teste",
    minutes: "min",
    hours: "h",
    monitoring: "Monitoramento",
    stabilizationStartTime: "Hora Inicio Estabilizacao",
    testEndTime: "Hora Termino Teste",
    initialPressure: "Pressao Inicial",
    finalPressure: "Pressao Final",
    pressureVariation: "Variacao de Pressao",
    results: "RESULTADOS",
    tightness: "Estanqueidade",
    noLeaks: "Nao houve vazamentos",
    noPressureDrop: "Nao houve queda de pressao",
    noVisibleDeformation: "Nao houve deformacao visivel",
    occurrences: "Ocorrencias",
    leaksFound: "Houve vazamento(s)",
    leaksDescription: "Descricao do(s) Vazamento(s)",
    pressureDropAboveAllowed: "Queda de pressao acima do permitido",
    structuralFailure: "Falha estrutural",
    failureDescription: "Descricao da Falha",
    photoEvidence: "REGISTRO FOTOGRAFICO",
    initialGaugePhotos: "Inicial - Manometro",
    initialGeneralPhotos: "Inicial - Visao Geral",
    duringTestPhotos: "Durante o Teste",
    finalGaugePhotos: "Final - Manometro",
    finalGeneralPhotos: "Final - Visao Geral",
    conclusion: "CONCLUSAO TECNICA",
    status: "Status",
    approved: "APROVADO",
    reproved: "REPROVADO",
    technicalConclusion: "Parecer Tecnico",
    declarationSignatures: "DECLARACAO E ASSINATURAS",
    declarationText: "Declaro que todas as informacoes prestadas neste relatorio sao verdadeiras e que o teste foi conduzido em conformidade com as normas aplicaveis.",
    technicalResponsibleSignature: "Responsavel Tecnico",
    inspectorSignature: "Inspetor",
    ownerRepSignature: "Representante Proprietario",
    date: "Data",
    yes: "Sim",
    no: "Nao",
    generatedBy: "Gerado por FireSafe ITM",
    geolocation: "Geolocalizacao",
    latitude: "Latitude",
    longitude: "Longitude",
    accuracy: "Precisao",
    meters: "m",
  },
};

export const generateHydrostaticTestHtml = async (options: HydrostaticPdfOptions): Promise<string> => {
  return generateHtml(options);
};

const generateHtml = async (options: HydrostaticPdfOptions): Promise<string> => {
  const { inspection, hydrostaticTest, photos, language } = options;
  
  const [photosWithBase64, logoDataUri] = await Promise.all([
    ensureAllPhotosBase64(photos),
    getLogoDataUri(),
  ]);
  const geoLocation = inspection?.geoLocation || hydrostaticTest.geoLocation;
  const t = translations[language];
  const h = hydrostaticTest;

  const checkIcon = (checked: boolean) => checked 
    ? '<span class="check-icon-yes">[X]</span>' 
    : '<span class="check-icon-no">[ ]</span>';

  const formatPressureReading = (point: string) => {
    if (point === "HIGHEST_POINT") return t.highestPoint;
    if (point === "NEAR_PUMP") return t.nearPump;
    if (point === "OTHER") return t.otherPoint;
    return point;
  };

  const formatFillingMethod = (method: string) => {
    if (method === "GRADUAL") return t.gradual;
    if (method === "BY_SECTOR") return t.bySector;
    return method;
  };

  const formatApprovedBy = (approvedBy: string) => {
    if (approvedBy === "CB") return t.cb;
    if (approvedBy === "FM") return t.fm;
    if (approvedBy === "OUTRO") return t.other;
    return approvedBy;
  };

  const formatWeather = (weather: string) => {
    if (weather === "ENSOLARADO") return t.weatherSunny;
    if (weather === "NUBLADO") return t.weatherCloudy;
    if (weather === "CHUVOSO") return t.weatherRainy;
    if (weather === "PARCIALMENTE_NUBLADO") return t.weatherPartlyCloudy;
    if (weather === "TEMPESTUOSO") return t.weatherStormy;
    return weather;
  };

  const normRefs = h.normRefs.map(ref => {
    if (ref === "NFPA_13") return "NFPA 13";
    if (ref === "NFPA_14") return "NFPA 14";
    if (ref === "NFPA_25") return "NFPA 25";
    if (ref === "FM_GLOBAL") return "FM Global" + (h.fmDataSheet ? ` (${h.fmDataSheet})` : "");
    if (ref === "NBR") return "NBR" + (h.nbrStandard ? ` ${h.nbrStandard}` : "");
    return ref;
  }).join(", ");

  const renderPhotoGrid = (categoryIds: string[], caption: string): string => {
    const categoryPhotos = photosWithBase64.filter(p => categoryIds.includes(p.id));
    if (categoryPhotos.length === 0) return "";

    let html = `<div class="photo-section"><h4>${sanitizeHtml(caption)}</h4><div class="photo-grid">`;
    
    for (const photo of categoryPhotos) {
      const base64 = photo.base64 || (photo.uri && photo.uri.startsWith("data:") ? photo.uri : null);
      if (base64) {
        html += `<div class="photo-item"><img src="${base64}" alt="${sanitizeHtml(caption)}" /><p class="photo-caption">${sanitizeHtml(caption)}</p></div>`;
      }
    }
    
    html += `</div></div>`;
    return html;
  };

  const getSignatureImage = (signatureData: string | undefined): string => {
    if (!signatureData) return "";
    
    // Check if signatureData is already a base64 data URI (signature captured directly)
    if (signatureData.startsWith("data:")) {
      return `<img src="${signatureData}" alt="Signature" class="signature-img" />`;
    }
    
    // Otherwise, try to find it in the photos array by ID
    const signaturePhoto = photosWithBase64.find(p => p.id === signatureData);
    if (!signaturePhoto) return "";
    const base64 = signaturePhoto.base64 || (signaturePhoto.uri && signaturePhoto.uri.startsWith("data:") ? signaturePhoto.uri : null);
    if (!base64) return "";
    return `<img src="${base64}" alt="Signature" class="signature-img" />`;
  };

  const technicalResponsibleSignatureHtml = getSignatureImage(h.signatures.technicalResponsibleSignatureId);
  const inspectorSignatureHtml = getSignatureImage(h.signatures.inspectorSignatureId);
  const ownerRepSignatureHtml = getSignatureImage(h.signatures.ownerRepSignatureId);

  const initialGaugePhotosHtml = renderPhotoGrid(h.photoEvidence.initialGaugePhotoIds || [], t.initialGaugePhotos);
  const initialGeneralPhotosHtml = renderPhotoGrid(h.photoEvidence.initialGeneralPhotoIds || [], t.initialGeneralPhotos);
  const duringTestPhotosHtml = renderPhotoGrid(h.photoEvidence.duringTestPhotoIds || [], t.duringTestPhotos);
  const finalGaugePhotosHtml = renderPhotoGrid(h.photoEvidence.finalGaugePhotoIds || [], t.finalGaugePhotos);
  const finalGeneralPhotosHtml = renderPhotoGrid(h.photoEvidence.finalGeneralPhotoIds || [], t.finalGeneralPhotos);

  const statusClass = h.conclusion.status === "APPROVED" ? "status-approved" : "status-reproved";
  const statusText = h.conclusion.status === "APPROVED" ? t.approved : t.reproved;

  const headerHtml = renderHeader({
    companyName: t.title,
    reportTitle: t.subtitle,
    showBadge: false,
    logoDataUri,
  });

  const bodyHtml = `
    <div class="section">
      <h2 class="section-title">${t.testIdentification}</h2>
    <div class="section-content">
      <div class="row">
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.systemType}</div>
            <div class="field-value">${h.systemType === "hydrants" ? t.hydrants : t.sprinklers}</div>
          </div>
        </div>
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.testDate}</div>
            <div class="field-value">${sanitizeHtml(h.testDate)}</div>
          </div>
        </div>
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.startTime} / ${t.endTime}</div>
            <div class="field-value">${sanitizeHtml(h.startTime)} - ${sanitizeHtml(h.endTime)}</div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.systemName}</div>
            <div class="field-value">${sanitizeHtml(h.systemName) || "-"}</div>
          </div>
        </div>
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.buildingType}</div>
            <div class="field-value">${sanitizeHtml(h.buildingType) || "-"}</div>
          </div>
        </div>
        <div class="col-3">
          <div class="field">
            <div class="field-label">${t.protectedArea}</div>
            <div class="field-value">${sanitizeHtml(h.protectedArea) || "-"}</div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-2">
          <div class="field">
            <div class="field-label">${t.normativeReferences}</div>
            <div class="field-value">${sanitizeHtml(normRefs)}</div>
          </div>
        </div>
        <div class="col-2">
          <div class="field">
            <div class="field-label">${t.approvedBy}</div>
            <div class="field-value">${formatApprovedBy(h.approvedBy || "")}${h.approvedBy === "OUTRO" && h.approvedByOtherText ? `: ${sanitizeHtml(h.approvedByOtherText)}` : ""}</div>
          </div>
        </div>
      </div>
      ${h.weather ? `<div class="field"><div class="field-label">${t.weather}</div><div class="field-value">${sanitizeHtml(formatWeather(h.weather))}</div></div>` : ""}
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.partiesInvolved}</h2>
    <div class="section-content">
      <div class="subsection">
        <div class="subsection-title">${t.owner}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.corporateName}</div>
              <div class="field-value">${sanitizeHtml(h.owner.corporateName)}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.address}</div>
              <div class="field-value">${sanitizeHtml(h.owner.address)}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.localResponsible}</div>
              <div class="field-value">${sanitizeHtml(h.owner.localResponsible)}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.role}</div>
              <div class="field-value">${sanitizeHtml(h.owner.role)}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.contact}</div>
              <div class="field-value">${sanitizeHtml(h.owner.contact)}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.executorCompany}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.corporateName}</div>
              <div class="field-value">${sanitizeHtml(h.executorCompany.corporateName)}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.cnpj}</div>
              <div class="field-value">${sanitizeHtml(h.executorCompany.cnpj)}</div>
            </div>
          </div>
        </div>
        <div class="field">
          <div class="field-label">${t.address}</div>
          <div class="field-value">${sanitizeHtml(h.executorCompany.address)}</div>
        </div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.technicalResponsible}</div>
        <div class="row">
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.name}</div>
              <div class="field-value">${sanitizeHtml(h.executorCompany.technicalResponsible.name)}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.creaCau}</div>
              <div class="field-value">${sanitizeHtml(h.executorCompany.technicalResponsible.creaCau)}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.artRrt}</div>
              <div class="field-value">${sanitizeHtml(h.executorCompany.technicalResponsible.artRrt) || "-"}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.inspector}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.name}</div>
              <div class="field-value">${sanitizeHtml(h.inspector.name)}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.role}</div>
              <div class="field-value">${sanitizeHtml(h.inspector.role)}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.preparation}</h2>
    <div class="section-content">
      <div class="subsection">
        <div class="subsection-title">${t.preChecks}</div>
        <div class="check-item">${checkIcon(h.preChecks.installedAsApprovedProject)} ${t.installedAsApprovedProject}</div>
        <div class="check-item">${checkIcon(h.preChecks.pipesAnchoredAndSupported)} ${t.pipesAnchoredAndSupported}</div>
        <div class="check-item">${checkIcon(h.preChecks.valvesCorrectlyInstalled)} ${t.valvesCorrectlyInstalled}</div>
        <div class="check-item">${checkIcon(h.preChecks.visibleConnectionsAccessible)} ${t.visibleConnectionsAccessible}</div>
        <div class="check-item">${checkIcon(h.preChecks.untestedSectionsIsolated)} ${t.untestedSectionsIsolated}</div>
        <div class="check-item">${checkIcon(h.preChecks.sensitiveEquipmentProtected)} ${t.sensitiveEquipmentProtected}</div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.instrumentation}</div>
        <div class="row">
          <div class="col-4">
            <div class="field">
              <div class="field-label">${t.manometerBrand}</div>
              <div class="field-value">${sanitizeHtml(h.instrumentation.manometerBrand) || "-"}</div>
            </div>
          </div>
          <div class="col-4">
            <div class="field">
              <div class="field-label">${t.manometerModel}</div>
              <div class="field-value">${sanitizeHtml(h.instrumentation.manometerModel) || "-"}</div>
            </div>
          </div>
          <div class="col-4">
            <div class="field">
              <div class="field-label">${t.measurementRange}</div>
              <div class="field-value">${sanitizeHtml(h.instrumentation.measurementRange) || "-"}</div>
            </div>
          </div>
          <div class="col-4">
            <div class="field">
              <div class="field-label">${t.calibrationCertificate}</div>
              <div class="field-value">${sanitizeHtml(h.instrumentation.calibrationCertificate) || "-"}</div>
            </div>
          </div>
        </div>
        <div class="field">
          <div class="field-label">${t.pressureReadingPoint}</div>
          <div class="field-value">${formatPressureReading(h.instrumentation.pressureReadingPoint)}${h.instrumentation.pressureReadingPoint === "OTHER" && h.instrumentation.pressureReadingPointOther ? `: ${sanitizeHtml(h.instrumentation.pressureReadingPointOther)}` : ""}</div>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.execution}</h2>
    <div class="section-content">
      <div class="subsection">
        <div class="subsection-title">${t.filling}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.fillingMethod}</div>
              <div class="field-value">${formatFillingMethod(h.filling.method)}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.airElimination}</div>
              <div class="check-item">${checkIcon(h.filling.airElimination.reliefValvesOpen)} ${t.reliefValvesOpen}</div>
              <div class="check-item">${checkIcon(h.filling.airElimination.purgersUsed)} ${t.purgersUsed}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.pressure}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.workingPressure}</div>
              <div class="field-value">${sanitizeHtml(h.pressure.workingPressureValue)} ${h.pressure.workingPressureUnit}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.testPressure}</div>
              <div class="field-value">${sanitizeHtml(h.pressure.testPressureValue)} ${h.pressure.testPressureUnit}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.minimumTestTime}</div>
              <div class="field-value">${sanitizeHtml(h.pressure.minimumTestTimeValue)} ${h.pressure.minimumTestTimeUnit === "minutes" ? t.minutes : t.hours}</div>
            </div>
          </div>
        </div>
        ${h.pressure.normativeCriteriaText ? `<div class="field"><div class="field-label">${t.normativeCriteria}</div><div class="field-value">${sanitizeHtml(h.pressure.normativeCriteriaText)}</div></div>` : ""}
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.monitoring}</div>
        <div class="row">
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.stabilizationStartTime}</div>
              <div class="field-value">${sanitizeHtml(h.monitoring.stabilizationStartTime) || "-"}</div>
            </div>
          </div>
          <div class="col-2">
            <div class="field">
              <div class="field-label">${t.testEndTime}</div>
              <div class="field-value">${sanitizeHtml(h.monitoring.testEndTime) || "-"}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.initialPressure}</div>
              <div class="field-value">${sanitizeHtml(h.monitoring.initialPressureValue)} ${h.monitoring.initialPressureUnit}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.finalPressure}</div>
              <div class="field-value">${sanitizeHtml(h.monitoring.finalPressureValue)} ${h.monitoring.finalPressureUnit}</div>
            </div>
          </div>
          <div class="col-3">
            <div class="field">
              <div class="field-label">${t.pressureVariation}</div>
              <div class="field-value">${sanitizeHtml(h.monitoring.pressureVariationValue)} ${h.monitoring.pressureVariationUnit}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.results}</h2>
    <div class="section-content">
      <div class="subsection">
        <div class="subsection-title">${t.tightness}</div>
        <div class="check-item">${checkIcon(h.results.noLeaks)} ${t.noLeaks}</div>
        <div class="check-item">${checkIcon(h.results.noPressureDrop)} ${t.noPressureDrop}</div>
        <div class="check-item">${checkIcon(h.results.noVisibleDeformation)} ${t.noVisibleDeformation}</div>
      </div>

      <div class="subsection">
        <div class="subsection-title">${t.occurrences}</div>
        <div class="check-item">${checkIcon(h.results.leaksFound)} ${t.leaksFound}</div>
        ${h.results.leaksFound && h.results.leaksDescription ? `<div class="field"><div class="field-label">${t.leaksDescription}</div><div class="field-value">${sanitizeHtml(h.results.leaksDescription)}</div></div>` : ""}
        <div class="check-item">${checkIcon(h.results.pressureDropAboveAllowed)} ${t.pressureDropAboveAllowed}</div>
        <div class="check-item">${checkIcon(h.results.structuralFailure)} ${t.structuralFailure}</div>
        ${h.results.structuralFailure && h.results.failureDescription ? `<div class="field"><div class="field-label">${t.failureDescription}</div><div class="field-value">${sanitizeHtml(h.results.failureDescription)}</div></div>` : ""}
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.photoEvidence}</h2>
    <div class="section-content">
      ${initialGaugePhotosHtml}
      ${initialGeneralPhotosHtml}
      ${duringTestPhotosHtml}
      ${finalGaugePhotosHtml}
      ${finalGeneralPhotosHtml}
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.conclusion}</h2>
    <div class="section-content">
      <div class="status-container">
        <span class="${statusClass}">${statusText}</span>
      </div>
      <div class="conclusion-text">${sanitizeHtml(h.conclusion.technicalConclusionText)}</div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">${t.declarationSignatures}</h2>
    <div class="section-content">
      <div class="declaration">${t.declarationText}</div>
      
      <div class="signature-section">
        <div class="signature-row">
          <div class="signature-box">
            ${technicalResponsibleSignatureHtml}
            <div class="signature-line">
              <div class="signature-label">${t.technicalResponsibleSignature}</div>
              <div class="signature-name">${sanitizeHtml(h.executorCompany.technicalResponsible.name)}</div>
              ${h.signatures.dates.technicalResponsibleDate ? `<div class="signature-date">${t.date}: ${sanitizeHtml(h.signatures.dates.technicalResponsibleDate)}</div>` : ""}
            </div>
          </div>
          <div class="signature-box">
            ${inspectorSignatureHtml}
            <div class="signature-line">
              <div class="signature-label">${t.inspectorSignature}</div>
              <div class="signature-name">${sanitizeHtml(h.inspector.name)}</div>
              ${h.signatures.dates.inspectorDate ? `<div class="signature-date">${t.date}: ${sanitizeHtml(h.signatures.dates.inspectorDate)}</div>` : ""}
            </div>
          </div>
        </div>
        <div class="signature-row">
          <div class="signature-box">
            ${ownerRepSignatureHtml}
            <div class="signature-line">
              <div class="signature-label">${t.ownerRepSignature}</div>
              <div class="signature-name">${sanitizeHtml(h.owner.localResponsible)}</div>
              ${h.signatures.dates.ownerRepDate ? `<div class="signature-date">${t.date}: ${sanitizeHtml(h.signatures.dates.ownerRepDate)}</div>` : ""}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  ${geoLocation && typeof geoLocation.latitude === 'number' && typeof geoLocation.longitude === 'number' ? `
    <div class="section">
      <h2 class="section-title">${t.geolocation}</h2>
      <div class="info-grid">
        <div class="info-item">
          <div class="info-label">${t.latitude}</div>
          <div class="info-value">${geoLocation.latitude.toFixed(6)}</div>
        </div>
        <div class="info-item">
          <div class="info-label">${t.longitude}</div>
          <div class="info-value">${geoLocation.longitude.toFixed(6)}</div>
        </div>
        ${typeof geoLocation.accuracy === 'number' ? `
        <div class="info-item">
          <div class="info-label">${t.accuracy}</div>
          <div class="info-value">${geoLocation.accuracy.toFixed(1)} ${t.meters}</div>
        </div>
        ` : ""}
      </div>
    </div>
  ` : ""}
  `;

  const footerHtml = renderFooter({
    generatedText: t.generatedBy,
    dateText: new Date().toLocaleDateString(language === "pt-BR" ? "pt-BR" : "en-US"),
    tagline: "",
  });

  return wrapDocument({
    title: `${t.title} - ${h.owner.corporateName}`,
    headerHtml,
    bodyHtml,
    footerHtml,
  });
};

export async function generateHydrostaticTestPdf(options: HydrostaticPdfOptions): Promise<string> {
  const html = await generateHtml(options);
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

export async function generateAndPrintHydrostaticTestPdf(options: HydrostaticPdfOptions): Promise<void> {
  const html = await generateHtml(options);
  await printHtml(html);
}

export async function generateAndShareHydrostaticTestPdf(options: HydrostaticPdfOptions): Promise<void> {
  const html = await generateHtml(options);
  await shareOrPrintHtml(
    html,
    options.language === "pt-BR" ? "Compartilhar Relatorio" : "Share Report",
  );
}

export async function generateAndEmailHydrostaticTestPdf(options: HydrostaticPdfOptions & { recipientEmail?: string }): Promise<void> {
  const uri = await generateHydrostaticTestPdf(options);
  const { hydrostaticTest, language } = options;
  
  const subject = language === "pt-BR" 
    ? `Relatorio Teste Hidrostatico - ${hydrostaticTest.owner.corporateName} - ${hydrostaticTest.testDate}`
    : `Hydrostatic Test Report - ${hydrostaticTest.owner.corporateName} - ${hydrostaticTest.testDate}`;
  
  const body = language === "pt-BR"
    ? `Segue em anexo o relatorio do teste hidrostatico realizado em ${hydrostaticTest.testDate}.\n\nAtenciosamente,\nFireSafe ITM`
    : `Please find attached the hydrostatic test report conducted on ${hydrostaticTest.testDate}.\n\nBest regards,\nFireSafe ITM`;

  await MailComposer.composeAsync({
    recipients: options.recipientEmail ? [options.recipientEmail] : [],
    subject,
    body,
    attachments: [uri],
  });
}
