// ARQUIVO GERADO AUTOMATICAMENTE — NAO EDITAR A MAO.
// Gerado por scripts/generate-app-templates.ts (npm run scheduler:app-templates).
// Agrega o golden NFPA 25 (docs/normas/golden.nfpa25.yaml) por (system x activity x frequency).
// Templates: 100 | Itens do golden cobertos: 1005.
import type { FrequencyUnit } from "@/server/scheduler/engine";

export interface ItmTemplate {
  /** Chave estavel do template (ex.: "wet_pipe-inspection-weekly"). */
  key: string;
  /** Slug do sistema (ex.: "wet_pipe"). */
  system: string;
  /** Atividade ITM: inspection | maintenance | test. */
  activity: string;
  /** Frequencia normativa (ex.: "weekly", "annual"). */
  frequency: string;
  /** Unidade do intervalo de recorrencia. */
  intervalUnit: FrequencyUnit;
  /** Quantidade de unidades do intervalo. */
  intervalCount: number;
  /** Quantos itens do golden este template agrega. */
  itemCount: number;
  /** Descricao legivel em portugues. */
  descriptionPt: string;
  /** Descricao legivel em ingles. */
  descriptionEn: string;
  /** Referencia normativa. */
  normativeRef: string;
  /** IDs do golden agregados neste template. */
  sourceRef: string[];
}

export const ITM_TEMPLATES: ItmTemplate[] = [
  {
    "key": "dry_pipe-inspection-5year",
    "system": "dry_pipe",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 4,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Sprinkler Tubo Seco",
    "descriptionEn": "Every 5 Years Inspection — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-INSPECTION-5YEAR-001",
      "NFPA25-DRYPIPE-INSPECTION-5YEAR-002",
      "NFPA25-DRYPIPE-INSPECTION-5YEAR-003",
      "NFPA25-DRYPIPE-INSPECTION-5YEAR-004"
    ]
  },
  {
    "key": "dry_pipe-inspection-annual",
    "system": "dry_pipe",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 19,
    "descriptionPt": "Inspeção Anual — Sprinkler Tubo Seco",
    "descriptionEn": "Annual Inspection — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-001",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-002",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-003",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-004",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-005",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-006",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-007",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-008",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-009",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-010",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-011",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-012",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-013",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-014",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-015",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-016",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-017",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-018",
      "NFPA25-DRYPIPE-INSPECTION-ANNUAL-019"
    ]
  },
  {
    "key": "dry_pipe-inspection-daily",
    "system": "dry_pipe",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Inspeção Diária — Sprinkler Tubo Seco",
    "descriptionEn": "Daily Inspection — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-INSPECTION-DAILY-001"
    ]
  },
  {
    "key": "dry_pipe-inspection-monthly",
    "system": "dry_pipe",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 35,
    "descriptionPt": "Inspeção Mensal — Sprinkler Tubo Seco",
    "descriptionEn": "Monthly Inspection — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-001",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-002",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-003",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-004",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-005",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-006",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-007",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-008",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-009",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-010",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-011",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-012",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-013",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-014",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-015",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-016",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-017",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-018",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-019",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-020",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-021",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-022",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-023",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-024",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-025",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-026",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-027",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-028",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-029",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-030",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-031",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-032",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-033",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-034",
      "NFPA25-DRYPIPE-INSPECTION-MONTHLY-035"
    ]
  },
  {
    "key": "dry_pipe-inspection-weekly",
    "system": "dry_pipe",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 13,
    "descriptionPt": "Inspeção Semanal — Sprinkler Tubo Seco",
    "descriptionEn": "Weekly Inspection — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-001",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-002",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-003",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-004",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-005",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-006",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-007",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-008",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-009",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-010",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-011",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-012",
      "NFPA25-DRYPIPE-INSPECTION-WEEKLY-013"
    ]
  },
  {
    "key": "dry_pipe-maintenance-annual",
    "system": "dry_pipe",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 3,
    "descriptionPt": "Manutenção Anual — Sprinkler Tubo Seco",
    "descriptionEn": "Annual Maintenance — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-MAINTENANCE-ANNUAL-001",
      "NFPA25-DRYPIPE-MAINTENANCE-ANNUAL-002",
      "NFPA25-DRYPIPE-MAINTENANCE-ANNUAL-003"
    ]
  },
  {
    "key": "dry_pipe-test-3year",
    "system": "dry_pipe",
    "activity": "test",
    "frequency": "3year",
    "intervalUnit": "year",
    "intervalCount": 3,
    "itemCount": 2,
    "descriptionPt": "Teste Trienal (3 anos) — Sprinkler Tubo Seco",
    "descriptionEn": "Every 3 Years Test — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-TEST-3YEAR-001",
      "NFPA25-DRYPIPE-TEST-3YEAR-002"
    ]
  },
  {
    "key": "dry_pipe-test-5year",
    "system": "dry_pipe",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Teste Quinquenal (5 anos) — Sprinkler Tubo Seco",
    "descriptionEn": "Every 5 Years Test — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-TEST-5YEAR-001",
      "NFPA25-DRYPIPE-TEST-5YEAR-002",
      "NFPA25-DRYPIPE-TEST-5YEAR-003"
    ]
  },
  {
    "key": "dry_pipe-test-annual",
    "system": "dry_pipe",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 11,
    "descriptionPt": "Teste Anual — Sprinkler Tubo Seco",
    "descriptionEn": "Annual Test — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-TEST-ANNUAL-001",
      "NFPA25-DRYPIPE-TEST-ANNUAL-002",
      "NFPA25-DRYPIPE-TEST-ANNUAL-003",
      "NFPA25-DRYPIPE-TEST-ANNUAL-004",
      "NFPA25-DRYPIPE-TEST-ANNUAL-005",
      "NFPA25-DRYPIPE-TEST-ANNUAL-006",
      "NFPA25-DRYPIPE-TEST-ANNUAL-007",
      "NFPA25-DRYPIPE-TEST-ANNUAL-008",
      "NFPA25-DRYPIPE-TEST-ANNUAL-009",
      "NFPA25-DRYPIPE-TEST-ANNUAL-010",
      "NFPA25-DRYPIPE-TEST-ANNUAL-011"
    ]
  },
  {
    "key": "dry_pipe-test-quarterly",
    "system": "dry_pipe",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 6,
    "descriptionPt": "Teste Trimestral — Sprinkler Tubo Seco",
    "descriptionEn": "Quarterly Test — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-TEST-QUARTERLY-001",
      "NFPA25-DRYPIPE-TEST-QUARTERLY-002",
      "NFPA25-DRYPIPE-TEST-QUARTERLY-003",
      "NFPA25-DRYPIPE-TEST-QUARTERLY-004",
      "NFPA25-DRYPIPE-TEST-QUARTERLY-005",
      "NFPA25-DRYPIPE-TEST-QUARTERLY-006"
    ]
  },
  {
    "key": "dry_pipe-test-semiannual",
    "system": "dry_pipe",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Sprinkler Tubo Seco",
    "descriptionEn": "Semiannual Test — Dry Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-DRYPIPE-TEST-SEMIANNUAL-001",
      "NFPA25-DRYPIPE-TEST-SEMIANNUAL-002"
    ]
  },
  {
    "key": "fire_pump-inspection-weekly",
    "system": "fire_pump",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 43,
    "descriptionPt": "Inspeção Semanal — Bomba de Incêndio",
    "descriptionEn": "Weekly Inspection — Fire Pump",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-001",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-002",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-003",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-004",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-005",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-006",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-007",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-008",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-009",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-010",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-011",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-012",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-013",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-014",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-015",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-016",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-017",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-018",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-019",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-020",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-021",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-022",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-023",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-024",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-025",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-026",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-027",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-028",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-029",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-030",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-031",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-032",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-033",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-034",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-035",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-036",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-037",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-038",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-039",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-040",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-041",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-042",
      "NFPA25-FIREPUMP-INSPECTION-WEEKLY-043"
    ]
  },
  {
    "key": "fire_pump-maintenance-annual",
    "system": "fire_pump",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 60,
    "descriptionPt": "Manutenção Anual — Bomba de Incêndio",
    "descriptionEn": "Annual Maintenance — Fire Pump",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-001",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-002",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-003",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-004",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-005",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-006",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-007",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-008",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-009",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-010",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-011",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-012",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-013",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-014",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-015",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-016",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-017",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-018",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-019",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-020",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-021",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-022",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-023",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-024",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-025",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-026",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-027",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-028",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-029",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-030",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-031",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-032",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-033",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-034",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-035",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-036",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-037",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-038",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-039",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-040",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-041",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-042",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-043",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-044",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-045",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-046",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-047",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-048",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-049",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-050",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-051",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-052",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-053",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-054",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-055",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-056",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-057",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-058",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-059",
      "NFPA25-FIREPUMP-MAINTENANCE-ANNUAL-060"
    ]
  },
  {
    "key": "fire_pump-maintenance-monthly",
    "system": "fire_pump",
    "activity": "maintenance",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 17,
    "descriptionPt": "Manutenção Mensal — Bomba de Incêndio",
    "descriptionEn": "Monthly Maintenance — Fire Pump",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-001",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-002",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-003",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-004",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-005",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-006",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-007",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-008",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-009",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-010",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-011",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-012",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-013",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-014",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-015",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-016",
      "NFPA25-FIREPUMP-MAINTENANCE-MONTHLY-017"
    ]
  },
  {
    "key": "fire_pump-maintenance-quarterly",
    "system": "fire_pump",
    "activity": "maintenance",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 6,
    "descriptionPt": "Manutenção Trimestral — Bomba de Incêndio",
    "descriptionEn": "Quarterly Maintenance — Fire Pump",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-001",
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-002",
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-003",
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-004",
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-005",
      "NFPA25-FIREPUMP-MAINTENANCE-QUARTERLY-006"
    ]
  },
  {
    "key": "fire_pump-maintenance-semiannual",
    "system": "fire_pump",
    "activity": "maintenance",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 5,
    "descriptionPt": "Manutenção Semestral — Bomba de Incêndio",
    "descriptionEn": "Semiannual Maintenance — Fire Pump",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FIREPUMP-MAINTENANCE-SEMIANNUAL-001",
      "NFPA25-FIREPUMP-MAINTENANCE-SEMIANNUAL-002",
      "NFPA25-FIREPUMP-MAINTENANCE-SEMIANNUAL-003",
      "NFPA25-FIREPUMP-MAINTENANCE-SEMIANNUAL-004",
      "NFPA25-FIREPUMP-MAINTENANCE-SEMIANNUAL-005"
    ]
  },
  {
    "key": "foam_water-inspection-5year",
    "system": "foam_water",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 6,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Espuma-Água",
    "descriptionEn": "Every 5 Years Inspection — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-001",
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-002",
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-003",
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-004",
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-005",
      "NFPA25-FOAMWATER-INSPECTION-5YEAR-006"
    ]
  },
  {
    "key": "foam_water-inspection-annual",
    "system": "foam_water",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 19,
    "descriptionPt": "Inspeção Anual — Espuma-Água",
    "descriptionEn": "Annual Inspection — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-001",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-002",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-003",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-004",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-005",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-006",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-007",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-008",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-009",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-010",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-011",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-012",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-013",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-014",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-015",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-016",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-017",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-018",
      "NFPA25-FOAMWATER-INSPECTION-ANNUAL-019"
    ]
  },
  {
    "key": "foam_water-inspection-daily",
    "system": "foam_water",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 18,
    "descriptionPt": "Inspeção Diária — Espuma-Água",
    "descriptionEn": "Daily Inspection — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-INSPECTION-DAILY-001",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-002",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-003",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-004",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-005",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-006",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-007",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-008",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-009",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-010",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-011",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-012",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-013",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-014",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-015",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-016",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-017",
      "NFPA25-FOAMWATER-INSPECTION-DAILY-018"
    ]
  },
  {
    "key": "foam_water-inspection-monthly",
    "system": "foam_water",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 22,
    "descriptionPt": "Inspeção Mensal — Espuma-Água",
    "descriptionEn": "Monthly Inspection — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-001",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-002",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-003",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-004",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-005",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-006",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-007",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-008",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-009",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-010",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-011",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-012",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-013",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-014",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-015",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-016",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-017",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-018",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-019",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-020",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-021",
      "NFPA25-FOAMWATER-INSPECTION-MONTHLY-022"
    ]
  },
  {
    "key": "foam_water-inspection-quarterly",
    "system": "foam_water",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 22,
    "descriptionPt": "Inspeção Trimestral — Espuma-Água",
    "descriptionEn": "Quarterly Inspection — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-001",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-002",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-003",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-004",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-005",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-006",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-007",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-008",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-009",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-010",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-011",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-012",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-013",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-014",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-015",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-016",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-017",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-018",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-019",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-020",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-021",
      "NFPA25-FOAMWATER-INSPECTION-QUARTERLY-022"
    ]
  },
  {
    "key": "foam_water-maintenance-annual",
    "system": "foam_water",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 8,
    "descriptionPt": "Manutenção Anual — Espuma-Água",
    "descriptionEn": "Annual Maintenance — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-001",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-002",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-003",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-004",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-005",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-006",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-007",
      "NFPA25-FOAMWATER-MAINTENANCE-ANNUAL-008"
    ]
  },
  {
    "key": "foam_water-test-3year",
    "system": "foam_water",
    "activity": "test",
    "frequency": "3year",
    "intervalUnit": "year",
    "intervalCount": 3,
    "itemCount": 2,
    "descriptionPt": "Teste Trienal (3 anos) — Espuma-Água",
    "descriptionEn": "Every 3 Years Test — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-TEST-3YEAR-001",
      "NFPA25-FOAMWATER-TEST-3YEAR-002"
    ]
  },
  {
    "key": "foam_water-test-5year",
    "system": "foam_water",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 1,
    "descriptionPt": "Teste Quinquenal (5 anos) — Espuma-Água",
    "descriptionEn": "Every 5 Years Test — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-TEST-5YEAR-001"
    ]
  },
  {
    "key": "foam_water-test-annual",
    "system": "foam_water",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 17,
    "descriptionPt": "Teste Anual — Espuma-Água",
    "descriptionEn": "Annual Test — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-TEST-ANNUAL-001",
      "NFPA25-FOAMWATER-TEST-ANNUAL-002",
      "NFPA25-FOAMWATER-TEST-ANNUAL-003",
      "NFPA25-FOAMWATER-TEST-ANNUAL-004",
      "NFPA25-FOAMWATER-TEST-ANNUAL-005",
      "NFPA25-FOAMWATER-TEST-ANNUAL-006",
      "NFPA25-FOAMWATER-TEST-ANNUAL-007",
      "NFPA25-FOAMWATER-TEST-ANNUAL-008",
      "NFPA25-FOAMWATER-TEST-ANNUAL-009",
      "NFPA25-FOAMWATER-TEST-ANNUAL-010",
      "NFPA25-FOAMWATER-TEST-ANNUAL-011",
      "NFPA25-FOAMWATER-TEST-ANNUAL-012",
      "NFPA25-FOAMWATER-TEST-ANNUAL-013",
      "NFPA25-FOAMWATER-TEST-ANNUAL-014",
      "NFPA25-FOAMWATER-TEST-ANNUAL-015",
      "NFPA25-FOAMWATER-TEST-ANNUAL-016",
      "NFPA25-FOAMWATER-TEST-ANNUAL-017"
    ]
  },
  {
    "key": "foam_water-test-quarterly",
    "system": "foam_water",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 7,
    "descriptionPt": "Teste Trimestral — Espuma-Água",
    "descriptionEn": "Quarterly Test — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-TEST-QUARTERLY-001",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-002",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-003",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-004",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-005",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-006",
      "NFPA25-FOAMWATER-TEST-QUARTERLY-007"
    ]
  },
  {
    "key": "foam_water-test-semiannual",
    "system": "foam_water",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Espuma-Água",
    "descriptionEn": "Semiannual Test — Foam-Water",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-FOAMWATER-TEST-SEMIANNUAL-001",
      "NFPA25-FOAMWATER-TEST-SEMIANNUAL-002"
    ]
  },
  {
    "key": "preaction_deluge-inspection-5year",
    "system": "preaction_deluge",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 5,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Pré-Ação/Dilúvio",
    "descriptionEn": "Every 5 Years Inspection — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-INSPECTION-5YEAR-001",
      "NFPA25-PREACTIONDELUGE-INSPECTION-5YEAR-002",
      "NFPA25-PREACTIONDELUGE-INSPECTION-5YEAR-003",
      "NFPA25-PREACTIONDELUGE-INSPECTION-5YEAR-004",
      "NFPA25-PREACTIONDELUGE-INSPECTION-5YEAR-005"
    ]
  },
  {
    "key": "preaction_deluge-inspection-annual",
    "system": "preaction_deluge",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 20,
    "descriptionPt": "Inspeção Anual — Pré-Ação/Dilúvio",
    "descriptionEn": "Annual Inspection — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-001",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-002",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-003",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-004",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-005",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-006",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-007",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-008",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-009",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-010",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-011",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-012",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-013",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-014",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-015",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-016",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-017",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-018",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-019",
      "NFPA25-PREACTIONDELUGE-INSPECTION-ANNUAL-020"
    ]
  },
  {
    "key": "preaction_deluge-inspection-monthly",
    "system": "preaction_deluge",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 14,
    "descriptionPt": "Inspeção Mensal — Pré-Ação/Dilúvio",
    "descriptionEn": "Monthly Inspection — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-001",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-002",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-003",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-004",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-005",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-006",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-007",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-008",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-009",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-010",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-011",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-012",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-013",
      "NFPA25-PREACTIONDELUGE-INSPECTION-MONTHLY-014"
    ]
  },
  {
    "key": "preaction_deluge-inspection-quarterly",
    "system": "preaction_deluge",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 24,
    "descriptionPt": "Inspeção Trimestral — Pré-Ação/Dilúvio",
    "descriptionEn": "Quarterly Inspection — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-001",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-002",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-003",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-004",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-005",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-006",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-007",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-008",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-009",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-010",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-011",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-012",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-013",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-014",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-015",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-016",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-017",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-018",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-019",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-020",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-021",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-022",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-023",
      "NFPA25-PREACTIONDELUGE-INSPECTION-QUARTERLY-024"
    ]
  },
  {
    "key": "preaction_deluge-inspection-weekly",
    "system": "preaction_deluge",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 13,
    "descriptionPt": "Inspeção Semanal — Pré-Ação/Dilúvio",
    "descriptionEn": "Weekly Inspection — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-001",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-002",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-003",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-004",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-005",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-006",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-007",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-008",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-009",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-010",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-011",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-012",
      "NFPA25-PREACTIONDELUGE-INSPECTION-WEEKLY-013"
    ]
  },
  {
    "key": "preaction_deluge-maintenance-annual",
    "system": "preaction_deluge",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 5,
    "descriptionPt": "Manutenção Anual — Pré-Ação/Dilúvio",
    "descriptionEn": "Annual Maintenance — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-MAINTENANCE-ANNUAL-001",
      "NFPA25-PREACTIONDELUGE-MAINTENANCE-ANNUAL-002",
      "NFPA25-PREACTIONDELUGE-MAINTENANCE-ANNUAL-003",
      "NFPA25-PREACTIONDELUGE-MAINTENANCE-ANNUAL-004",
      "NFPA25-PREACTIONDELUGE-MAINTENANCE-ANNUAL-005"
    ]
  },
  {
    "key": "preaction_deluge-test-3year",
    "system": "preaction_deluge",
    "activity": "test",
    "frequency": "3year",
    "intervalUnit": "year",
    "intervalCount": 3,
    "itemCount": 2,
    "descriptionPt": "Teste Trienal (3 anos) — Pré-Ação/Dilúvio",
    "descriptionEn": "Every 3 Years Test — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-TEST-3YEAR-001",
      "NFPA25-PREACTIONDELUGE-TEST-3YEAR-002"
    ]
  },
  {
    "key": "preaction_deluge-test-5year",
    "system": "preaction_deluge",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Teste Quinquenal (5 anos) — Pré-Ação/Dilúvio",
    "descriptionEn": "Every 5 Years Test — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-TEST-5YEAR-001",
      "NFPA25-PREACTIONDELUGE-TEST-5YEAR-002",
      "NFPA25-PREACTIONDELUGE-TEST-5YEAR-003"
    ]
  },
  {
    "key": "preaction_deluge-test-annual",
    "system": "preaction_deluge",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 16,
    "descriptionPt": "Teste Anual — Pré-Ação/Dilúvio",
    "descriptionEn": "Annual Test — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-001",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-002",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-003",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-004",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-005",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-006",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-007",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-008",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-009",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-010",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-011",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-012",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-013",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-014",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-015",
      "NFPA25-PREACTIONDELUGE-TEST-ANNUAL-016"
    ]
  },
  {
    "key": "preaction_deluge-test-quarterly",
    "system": "preaction_deluge",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 7,
    "descriptionPt": "Teste Trimestral — Pré-Ação/Dilúvio",
    "descriptionEn": "Quarterly Test — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-001",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-002",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-003",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-004",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-005",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-006",
      "NFPA25-PREACTIONDELUGE-TEST-QUARTERLY-007"
    ]
  },
  {
    "key": "preaction_deluge-test-semiannual",
    "system": "preaction_deluge",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Pré-Ação/Dilúvio",
    "descriptionEn": "Semiannual Test — Preaction/Deluge",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PREACTIONDELUGE-TEST-SEMIANNUAL-001",
      "NFPA25-PREACTIONDELUGE-TEST-SEMIANNUAL-002"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-5year",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Redes Privadas de Incêndio",
    "descriptionEn": "Every 5 Years Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-5YEAR-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-5YEAR-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-5YEAR-003"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-annual",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 24,
    "descriptionPt": "Inspeção Anual — Redes Privadas de Incêndio",
    "descriptionEn": "Annual Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-006",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-007",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-008",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-009",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-010",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-011",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-012",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-013",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-014",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-015",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-016",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-017",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-018",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-019",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-020",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-021",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-022",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-023",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-ANNUAL-024"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-monthly",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 6,
    "descriptionPt": "Inspeção Mensal — Redes Privadas de Incêndio",
    "descriptionEn": "Monthly Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-MONTHLY-006"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-quarterly",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 21,
    "descriptionPt": "Inspeção Trimestral — Redes Privadas de Incêndio",
    "descriptionEn": "Quarterly Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-006",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-007",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-008",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-009",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-010",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-011",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-012",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-013",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-014",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-015",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-016",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-017",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-018",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-019",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-020",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-QUARTERLY-021"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-semiannual",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 4,
    "descriptionPt": "Inspeção Semestral — Redes Privadas de Incêndio",
    "descriptionEn": "Semiannual Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-SEMIANNUAL-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-SEMIANNUAL-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-SEMIANNUAL-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-SEMIANNUAL-004"
    ]
  },
  {
    "key": "private_fire_service_mains-inspection-weekly",
    "system": "private_fire_service_mains",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 8,
    "descriptionPt": "Inspeção Semanal — Redes Privadas de Incêndio",
    "descriptionEn": "Weekly Inspection — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-006",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-007",
      "NFPA25-PRIVATEFIRESERVICEMAINS-INSPECTION-WEEKLY-008"
    ]
  },
  {
    "key": "private_fire_service_mains-test-5year",
    "system": "private_fire_service_mains",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 8,
    "descriptionPt": "Teste Quinquenal (5 anos) — Redes Privadas de Incêndio",
    "descriptionEn": "Every 5 Years Test — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-006",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-007",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-5YEAR-008"
    ]
  },
  {
    "key": "private_fire_service_mains-test-annual",
    "system": "private_fire_service_mains",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 7,
    "descriptionPt": "Teste Anual — Redes Privadas de Incêndio",
    "descriptionEn": "Annual Test — Private Fire Service Mains",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-001",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-002",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-003",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-004",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-005",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-006",
      "NFPA25-PRIVATEFIRESERVICEMAINS-TEST-ANNUAL-007"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-5year",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 4,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Coluna e Mangueira",
    "descriptionEn": "Every 5 Years Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-5YEAR-001",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-5YEAR-002",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-5YEAR-003",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-5YEAR-004"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-annual",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 20,
    "descriptionPt": "Inspeção Anual — Coluna e Mangueira",
    "descriptionEn": "Annual Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-001",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-002",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-003",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-004",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-005",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-006",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-007",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-008",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-009",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-010",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-011",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-012",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-013",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-014",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-015",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-016",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-017",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-018",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-019",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-ANNUAL-020"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-daily",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Inspeção Diária — Coluna e Mangueira",
    "descriptionEn": "Daily Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-DAILY-001"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-monthly",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 4,
    "descriptionPt": "Inspeção Mensal — Coluna e Mangueira",
    "descriptionEn": "Monthly Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-MONTHLY-001",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-MONTHLY-002",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-MONTHLY-003",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-MONTHLY-004"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-quarterly",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 17,
    "descriptionPt": "Inspeção Trimestral — Coluna e Mangueira",
    "descriptionEn": "Quarterly Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-001",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-002",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-003",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-004",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-005",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-006",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-007",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-008",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-009",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-010",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-011",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-012",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-013",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-014",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-015",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-016",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-QUARTERLY-017"
    ]
  },
  {
    "key": "standpipe_and_hose-inspection-weekly",
    "system": "standpipe_and_hose",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 13,
    "descriptionPt": "Inspeção Semanal — Coluna e Mangueira",
    "descriptionEn": "Weekly Inspection — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-001",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-002",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-003",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-004",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-005",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-006",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-007",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-008",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-009",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-010",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-011",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-012",
      "NFPA25-STANDPIPEANDHOSE-INSPECTION-WEEKLY-013"
    ]
  },
  {
    "key": "standpipe_and_hose-maintenance-annual",
    "system": "standpipe_and_hose",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 4,
    "descriptionPt": "Manutenção Anual — Coluna e Mangueira",
    "descriptionEn": "Annual Maintenance — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-MAINTENANCE-ANNUAL-001",
      "NFPA25-STANDPIPEANDHOSE-MAINTENANCE-ANNUAL-002",
      "NFPA25-STANDPIPEANDHOSE-MAINTENANCE-ANNUAL-003",
      "NFPA25-STANDPIPEANDHOSE-MAINTENANCE-ANNUAL-004"
    ]
  },
  {
    "key": "standpipe_and_hose-test-3year",
    "system": "standpipe_and_hose",
    "activity": "test",
    "frequency": "3year",
    "intervalUnit": "year",
    "intervalCount": 3,
    "itemCount": 4,
    "descriptionPt": "Teste Trienal (3 anos) — Coluna e Mangueira",
    "descriptionEn": "Every 3 Years Test — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-TEST-3YEAR-001",
      "NFPA25-STANDPIPEANDHOSE-TEST-3YEAR-002",
      "NFPA25-STANDPIPEANDHOSE-TEST-3YEAR-003",
      "NFPA25-STANDPIPEANDHOSE-TEST-3YEAR-004"
    ]
  },
  {
    "key": "standpipe_and_hose-test-5year",
    "system": "standpipe_and_hose",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 5,
    "descriptionPt": "Teste Quinquenal (5 anos) — Coluna e Mangueira",
    "descriptionEn": "Every 5 Years Test — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-TEST-5YEAR-001",
      "NFPA25-STANDPIPEANDHOSE-TEST-5YEAR-002",
      "NFPA25-STANDPIPEANDHOSE-TEST-5YEAR-003",
      "NFPA25-STANDPIPEANDHOSE-TEST-5YEAR-004",
      "NFPA25-STANDPIPEANDHOSE-TEST-5YEAR-005"
    ]
  },
  {
    "key": "standpipe_and_hose-test-annual",
    "system": "standpipe_and_hose",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 15,
    "descriptionPt": "Teste Anual — Coluna e Mangueira",
    "descriptionEn": "Annual Test — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-001",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-002",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-003",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-004",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-005",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-006",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-007",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-008",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-009",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-010",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-011",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-012",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-013",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-014",
      "NFPA25-STANDPIPEANDHOSE-TEST-ANNUAL-015"
    ]
  },
  {
    "key": "standpipe_and_hose-test-quarterly",
    "system": "standpipe_and_hose",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 6,
    "descriptionPt": "Teste Trimestral — Coluna e Mangueira",
    "descriptionEn": "Quarterly Test — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-001",
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-002",
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-003",
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-004",
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-005",
      "NFPA25-STANDPIPEANDHOSE-TEST-QUARTERLY-006"
    ]
  },
  {
    "key": "standpipe_and_hose-test-semiannual",
    "system": "standpipe_and_hose",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Coluna e Mangueira",
    "descriptionEn": "Semiannual Test — Standpipe and Hose",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-STANDPIPEANDHOSE-TEST-SEMIANNUAL-001",
      "NFPA25-STANDPIPEANDHOSE-TEST-SEMIANNUAL-002"
    ]
  },
  {
    "key": "water_mist-inspection-5year",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 5,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Neblina de Água",
    "descriptionEn": "Every 5 Years Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-5YEAR-001",
      "NFPA25-WATERMIST-INSPECTION-5YEAR-002",
      "NFPA25-WATERMIST-INSPECTION-5YEAR-003",
      "NFPA25-WATERMIST-INSPECTION-5YEAR-004",
      "NFPA25-WATERMIST-INSPECTION-5YEAR-005"
    ]
  },
  {
    "key": "water_mist-inspection-annual",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 28,
    "descriptionPt": "Inspeção Anual — Neblina de Água",
    "descriptionEn": "Annual Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-001",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-002",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-003",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-004",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-005",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-006",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-007",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-008",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-009",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-010",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-011",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-012",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-013",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-014",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-015",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-016",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-017",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-018",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-019",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-020",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-021",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-022",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-023",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-024",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-025",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-026",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-027",
      "NFPA25-WATERMIST-INSPECTION-ANNUAL-028"
    ]
  },
  {
    "key": "water_mist-inspection-daily",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Inspeção Diária — Neblina de Água",
    "descriptionEn": "Daily Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-DAILY-001"
    ]
  },
  {
    "key": "water_mist-inspection-monthly",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 35,
    "descriptionPt": "Inspeção Mensal — Neblina de Água",
    "descriptionEn": "Monthly Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-001",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-002",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-003",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-004",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-005",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-006",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-007",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-008",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-009",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-010",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-011",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-012",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-013",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-014",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-015",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-016",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-017",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-018",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-019",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-020",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-021",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-022",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-023",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-024",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-025",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-026",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-027",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-028",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-029",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-030",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-031",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-032",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-033",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-034",
      "NFPA25-WATERMIST-INSPECTION-MONTHLY-035"
    ]
  },
  {
    "key": "water_mist-inspection-quarterly",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 6,
    "descriptionPt": "Inspeção Trimestral — Neblina de Água",
    "descriptionEn": "Quarterly Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-001",
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-002",
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-003",
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-004",
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-005",
      "NFPA25-WATERMIST-INSPECTION-QUARTERLY-006"
    ]
  },
  {
    "key": "water_mist-inspection-semiannual",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 7,
    "descriptionPt": "Inspeção Semestral — Neblina de Água",
    "descriptionEn": "Semiannual Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-001",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-002",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-003",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-004",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-005",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-006",
      "NFPA25-WATERMIST-INSPECTION-SEMIANNUAL-007"
    ]
  },
  {
    "key": "water_mist-inspection-weekly",
    "system": "water_mist",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 13,
    "descriptionPt": "Inspeção Semanal — Neblina de Água",
    "descriptionEn": "Weekly Inspection — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-001",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-002",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-003",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-004",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-005",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-006",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-007",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-008",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-009",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-010",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-011",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-012",
      "NFPA25-WATERMIST-INSPECTION-WEEKLY-013"
    ]
  },
  {
    "key": "water_mist-maintenance-annual",
    "system": "water_mist",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 6,
    "descriptionPt": "Manutenção Anual — Neblina de Água",
    "descriptionEn": "Annual Maintenance — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-001",
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-002",
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-003",
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-004",
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-005",
      "NFPA25-WATERMIST-MAINTENANCE-ANNUAL-006"
    ]
  },
  {
    "key": "water_mist-test-5year",
    "system": "water_mist",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Teste Quinquenal (5 anos) — Neblina de Água",
    "descriptionEn": "Every 5 Years Test — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-TEST-5YEAR-001",
      "NFPA25-WATERMIST-TEST-5YEAR-002",
      "NFPA25-WATERMIST-TEST-5YEAR-003"
    ]
  },
  {
    "key": "water_mist-test-annual",
    "system": "water_mist",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 20,
    "descriptionPt": "Teste Anual — Neblina de Água",
    "descriptionEn": "Annual Test — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-TEST-ANNUAL-001",
      "NFPA25-WATERMIST-TEST-ANNUAL-002",
      "NFPA25-WATERMIST-TEST-ANNUAL-003",
      "NFPA25-WATERMIST-TEST-ANNUAL-004",
      "NFPA25-WATERMIST-TEST-ANNUAL-005",
      "NFPA25-WATERMIST-TEST-ANNUAL-006",
      "NFPA25-WATERMIST-TEST-ANNUAL-007",
      "NFPA25-WATERMIST-TEST-ANNUAL-008",
      "NFPA25-WATERMIST-TEST-ANNUAL-009",
      "NFPA25-WATERMIST-TEST-ANNUAL-010",
      "NFPA25-WATERMIST-TEST-ANNUAL-011",
      "NFPA25-WATERMIST-TEST-ANNUAL-012",
      "NFPA25-WATERMIST-TEST-ANNUAL-013",
      "NFPA25-WATERMIST-TEST-ANNUAL-014",
      "NFPA25-WATERMIST-TEST-ANNUAL-015",
      "NFPA25-WATERMIST-TEST-ANNUAL-016",
      "NFPA25-WATERMIST-TEST-ANNUAL-017",
      "NFPA25-WATERMIST-TEST-ANNUAL-018",
      "NFPA25-WATERMIST-TEST-ANNUAL-019",
      "NFPA25-WATERMIST-TEST-ANNUAL-020"
    ]
  },
  {
    "key": "water_mist-test-quarterly",
    "system": "water_mist",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 1,
    "descriptionPt": "Teste Trimestral — Neblina de Água",
    "descriptionEn": "Quarterly Test — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-TEST-QUARTERLY-001"
    ]
  },
  {
    "key": "water_mist-test-semiannual",
    "system": "water_mist",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 3,
    "descriptionPt": "Teste Semestral — Neblina de Água",
    "descriptionEn": "Semiannual Test — Water Mist",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERMIST-TEST-SEMIANNUAL-001",
      "NFPA25-WATERMIST-TEST-SEMIANNUAL-002",
      "NFPA25-WATERMIST-TEST-SEMIANNUAL-003"
    ]
  },
  {
    "key": "water_spray-inspection-5year",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Spray de Água",
    "descriptionEn": "Every 5 Years Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-5YEAR-001",
      "NFPA25-WATERSPRAY-INSPECTION-5YEAR-002",
      "NFPA25-WATERSPRAY-INSPECTION-5YEAR-003"
    ]
  },
  {
    "key": "water_spray-inspection-annual",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 16,
    "descriptionPt": "Inspeção Anual — Spray de Água",
    "descriptionEn": "Annual Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-001",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-002",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-003",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-004",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-005",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-006",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-007",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-008",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-009",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-010",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-011",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-012",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-013",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-014",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-015",
      "NFPA25-WATERSPRAY-INSPECTION-ANNUAL-016"
    ]
  },
  {
    "key": "water_spray-inspection-daily",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Inspeção Diária — Spray de Água",
    "descriptionEn": "Daily Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-DAILY-001"
    ]
  },
  {
    "key": "water_spray-inspection-monthly",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 15,
    "descriptionPt": "Inspeção Mensal — Spray de Água",
    "descriptionEn": "Monthly Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-001",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-002",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-003",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-004",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-005",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-006",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-007",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-008",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-009",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-010",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-011",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-012",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-013",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-014",
      "NFPA25-WATERSPRAY-INSPECTION-MONTHLY-015"
    ]
  },
  {
    "key": "water_spray-inspection-quarterly",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 10,
    "descriptionPt": "Inspeção Trimestral — Spray de Água",
    "descriptionEn": "Quarterly Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-001",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-002",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-003",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-004",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-005",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-006",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-007",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-008",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-009",
      "NFPA25-WATERSPRAY-INSPECTION-QUARTERLY-010"
    ]
  },
  {
    "key": "water_spray-inspection-weekly",
    "system": "water_spray",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 9,
    "descriptionPt": "Inspeção Semanal — Spray de Água",
    "descriptionEn": "Weekly Inspection — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-001",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-002",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-003",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-004",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-005",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-006",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-007",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-008",
      "NFPA25-WATERSPRAY-INSPECTION-WEEKLY-009"
    ]
  },
  {
    "key": "water_spray-maintenance-annual",
    "system": "water_spray",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Manutenção Anual — Spray de Água",
    "descriptionEn": "Annual Maintenance — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-MAINTENANCE-ANNUAL-001"
    ]
  },
  {
    "key": "water_spray-test-annual",
    "system": "water_spray",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 17,
    "descriptionPt": "Teste Anual — Spray de Água",
    "descriptionEn": "Annual Test — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-TEST-ANNUAL-001",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-002",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-003",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-004",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-005",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-006",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-007",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-008",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-009",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-010",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-011",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-012",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-013",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-014",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-015",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-016",
      "NFPA25-WATERSPRAY-TEST-ANNUAL-017"
    ]
  },
  {
    "key": "water_spray-test-quarterly",
    "system": "water_spray",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 5,
    "descriptionPt": "Teste Trimestral — Spray de Água",
    "descriptionEn": "Quarterly Test — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-TEST-QUARTERLY-001",
      "NFPA25-WATERSPRAY-TEST-QUARTERLY-002",
      "NFPA25-WATERSPRAY-TEST-QUARTERLY-003",
      "NFPA25-WATERSPRAY-TEST-QUARTERLY-004",
      "NFPA25-WATERSPRAY-TEST-QUARTERLY-005"
    ]
  },
  {
    "key": "water_spray-test-semiannual",
    "system": "water_spray",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Spray de Água",
    "descriptionEn": "Semiannual Test — Water Spray",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSPRAY-TEST-SEMIANNUAL-001",
      "NFPA25-WATERSPRAY-TEST-SEMIANNUAL-002"
    ]
  },
  {
    "key": "water_storage_tank-inspection-5year",
    "system": "water_storage_tank",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 11,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Tanque de Armazenamento de Água",
    "descriptionEn": "Every 5 Years Inspection — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-001",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-002",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-003",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-004",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-005",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-006",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-007",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-008",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-009",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-010",
      "NFPA25-WATERSTORAGETANK-INSPECTION-5YEAR-011"
    ]
  },
  {
    "key": "water_storage_tank-inspection-annual",
    "system": "water_storage_tank",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 10,
    "descriptionPt": "Inspeção Anual — Tanque de Armazenamento de Água",
    "descriptionEn": "Annual Inspection — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-001",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-002",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-003",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-004",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-005",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-006",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-007",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-008",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-009",
      "NFPA25-WATERSTORAGETANK-INSPECTION-ANNUAL-010"
    ]
  },
  {
    "key": "water_storage_tank-inspection-daily",
    "system": "water_storage_tank",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 9,
    "descriptionPt": "Inspeção Diária — Tanque de Armazenamento de Água",
    "descriptionEn": "Daily Inspection — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-001",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-002",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-003",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-004",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-005",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-006",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-007",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-008",
      "NFPA25-WATERSTORAGETANK-INSPECTION-DAILY-009"
    ]
  },
  {
    "key": "water_storage_tank-inspection-monthly",
    "system": "water_storage_tank",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 9,
    "descriptionPt": "Inspeção Mensal — Tanque de Armazenamento de Água",
    "descriptionEn": "Monthly Inspection — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-001",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-002",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-003",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-004",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-005",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-006",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-007",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-008",
      "NFPA25-WATERSTORAGETANK-INSPECTION-MONTHLY-009"
    ]
  },
  {
    "key": "water_storage_tank-inspection-quarterly",
    "system": "water_storage_tank",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 18,
    "descriptionPt": "Inspeção Trimestral — Tanque de Armazenamento de Água",
    "descriptionEn": "Quarterly Inspection — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-001",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-002",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-003",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-004",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-005",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-006",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-007",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-008",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-009",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-010",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-011",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-012",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-013",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-014",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-015",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-016",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-017",
      "NFPA25-WATERSTORAGETANK-INSPECTION-QUARTERLY-018"
    ]
  },
  {
    "key": "water_storage_tank-test-5year",
    "system": "water_storage_tank",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 6,
    "descriptionPt": "Teste Quinquenal (5 anos) — Tanque de Armazenamento de Água",
    "descriptionEn": "Every 5 Years Test — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-001",
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-002",
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-003",
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-004",
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-005",
      "NFPA25-WATERSTORAGETANK-TEST-5YEAR-006"
    ]
  },
  {
    "key": "water_storage_tank-test-annual",
    "system": "water_storage_tank",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 4,
    "descriptionPt": "Teste Anual — Tanque de Armazenamento de Água",
    "descriptionEn": "Annual Test — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-TEST-ANNUAL-001",
      "NFPA25-WATERSTORAGETANK-TEST-ANNUAL-002",
      "NFPA25-WATERSTORAGETANK-TEST-ANNUAL-003",
      "NFPA25-WATERSTORAGETANK-TEST-ANNUAL-004"
    ]
  },
  {
    "key": "water_storage_tank-test-monthly",
    "system": "water_storage_tank",
    "activity": "test",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 2,
    "descriptionPt": "Teste Mensal — Tanque de Armazenamento de Água",
    "descriptionEn": "Monthly Test — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-TEST-MONTHLY-001",
      "NFPA25-WATERSTORAGETANK-TEST-MONTHLY-002"
    ]
  },
  {
    "key": "water_storage_tank-test-semiannual",
    "system": "water_storage_tank",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 1,
    "descriptionPt": "Teste Semestral — Tanque de Armazenamento de Água",
    "descriptionEn": "Semiannual Test — Water Storage Tank",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WATERSTORAGETANK-TEST-SEMIANNUAL-001"
    ]
  },
  {
    "key": "wet_pipe-inspection-5year",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 4,
    "descriptionPt": "Inspeção Quinquenal (5 anos) — Sprinkler Tubo Molhado",
    "descriptionEn": "Every 5 Years Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-5YEAR-001",
      "NFPA25-WETPIPE-INSPECTION-5YEAR-002",
      "NFPA25-WETPIPE-INSPECTION-5YEAR-003",
      "NFPA25-WETPIPE-INSPECTION-5YEAR-004"
    ]
  },
  {
    "key": "wet_pipe-inspection-annual",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 17,
    "descriptionPt": "Inspeção Anual — Sprinkler Tubo Molhado",
    "descriptionEn": "Annual Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-001",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-002",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-003",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-004",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-005",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-006",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-007",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-008",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-009",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-010",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-011",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-012",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-013",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-014",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-015",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-016",
      "NFPA25-WETPIPE-INSPECTION-ANNUAL-017"
    ]
  },
  {
    "key": "wet_pipe-inspection-daily",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "daily",
    "intervalUnit": "day",
    "intervalCount": 1,
    "itemCount": 1,
    "descriptionPt": "Inspeção Diária — Sprinkler Tubo Molhado",
    "descriptionEn": "Daily Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-DAILY-001"
    ]
  },
  {
    "key": "wet_pipe-inspection-monthly",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "monthly",
    "intervalUnit": "month",
    "intervalCount": 1,
    "itemCount": 8,
    "descriptionPt": "Inspeção Mensal — Sprinkler Tubo Molhado",
    "descriptionEn": "Monthly Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-001",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-002",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-003",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-004",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-005",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-006",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-007",
      "NFPA25-WETPIPE-INSPECTION-MONTHLY-008"
    ]
  },
  {
    "key": "wet_pipe-inspection-quarterly",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 26,
    "descriptionPt": "Inspeção Trimestral — Sprinkler Tubo Molhado",
    "descriptionEn": "Quarterly Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-001",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-002",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-003",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-004",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-005",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-006",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-007",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-008",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-009",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-010",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-011",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-012",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-013",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-014",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-015",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-016",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-017",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-018",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-019",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-020",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-021",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-022",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-023",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-024",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-025",
      "NFPA25-WETPIPE-INSPECTION-QUARTERLY-026"
    ]
  },
  {
    "key": "wet_pipe-inspection-weekly",
    "system": "wet_pipe",
    "activity": "inspection",
    "frequency": "weekly",
    "intervalUnit": "week",
    "intervalCount": 1,
    "itemCount": 12,
    "descriptionPt": "Inspeção Semanal — Sprinkler Tubo Molhado",
    "descriptionEn": "Weekly Inspection — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-001",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-002",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-003",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-004",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-005",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-006",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-007",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-008",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-009",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-010",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-011",
      "NFPA25-WETPIPE-INSPECTION-WEEKLY-012"
    ]
  },
  {
    "key": "wet_pipe-maintenance-annual",
    "system": "wet_pipe",
    "activity": "maintenance",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 2,
    "descriptionPt": "Manutenção Anual — Sprinkler Tubo Molhado",
    "descriptionEn": "Annual Maintenance — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-MAINTENANCE-ANNUAL-001",
      "NFPA25-WETPIPE-MAINTENANCE-ANNUAL-002"
    ]
  },
  {
    "key": "wet_pipe-test-5year",
    "system": "wet_pipe",
    "activity": "test",
    "frequency": "5year",
    "intervalUnit": "year",
    "intervalCount": 5,
    "itemCount": 3,
    "descriptionPt": "Teste Quinquenal (5 anos) — Sprinkler Tubo Molhado",
    "descriptionEn": "Every 5 Years Test — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-TEST-5YEAR-001",
      "NFPA25-WETPIPE-TEST-5YEAR-002",
      "NFPA25-WETPIPE-TEST-5YEAR-003"
    ]
  },
  {
    "key": "wet_pipe-test-annual",
    "system": "wet_pipe",
    "activity": "test",
    "frequency": "annual",
    "intervalUnit": "year",
    "intervalCount": 1,
    "itemCount": 8,
    "descriptionPt": "Teste Anual — Sprinkler Tubo Molhado",
    "descriptionEn": "Annual Test — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-TEST-ANNUAL-001",
      "NFPA25-WETPIPE-TEST-ANNUAL-002",
      "NFPA25-WETPIPE-TEST-ANNUAL-003",
      "NFPA25-WETPIPE-TEST-ANNUAL-004",
      "NFPA25-WETPIPE-TEST-ANNUAL-005",
      "NFPA25-WETPIPE-TEST-ANNUAL-006",
      "NFPA25-WETPIPE-TEST-ANNUAL-007",
      "NFPA25-WETPIPE-TEST-ANNUAL-008"
    ]
  },
  {
    "key": "wet_pipe-test-quarterly",
    "system": "wet_pipe",
    "activity": "test",
    "frequency": "quarterly",
    "intervalUnit": "month",
    "intervalCount": 3,
    "itemCount": 4,
    "descriptionPt": "Teste Trimestral — Sprinkler Tubo Molhado",
    "descriptionEn": "Quarterly Test — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-TEST-QUARTERLY-001",
      "NFPA25-WETPIPE-TEST-QUARTERLY-002",
      "NFPA25-WETPIPE-TEST-QUARTERLY-003",
      "NFPA25-WETPIPE-TEST-QUARTERLY-004"
    ]
  },
  {
    "key": "wet_pipe-test-semiannual",
    "system": "wet_pipe",
    "activity": "test",
    "frequency": "semiannual",
    "intervalUnit": "month",
    "intervalCount": 6,
    "itemCount": 2,
    "descriptionPt": "Teste Semestral — Sprinkler Tubo Molhado",
    "descriptionEn": "Semiannual Test — Wet Pipe Sprinkler",
    "normativeRef": "NFPA 25 (2019), eForms",
    "sourceRef": [
      "NFPA25-WETPIPE-TEST-SEMIANNUAL-001",
      "NFPA25-WETPIPE-TEST-SEMIANNUAL-002"
    ]
  }
];
